apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: halloween
spec:
  homepage: https://github.com/scraly/kubectl-halloween
  shortDescription: Display Hallowen emoji randomly before resources name
  version: v0.0.1
  description: |
    This plugin allows you to add randomly a Halloween emoji just before the resources name. It's a special Halloween mode.
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    uri: https://github.com/scraly/kubectl-halloween/archive/v0.0.1.tar.gz
    # sha256: 8f68e19b841a1f1492536dc27f9b93ea3204c7e4fd0ad2e3c483d1b8e95be675
    bin: kubectl-halloween