#!/bin/bash

##########################################################################
# kubectl-halloween                                                      #
#                                                                        #
# Welcome in Halloween plugin for kubectl Kubernetes CLI                 #
# which display randomly an emoji in the beginning of the resources name #
#                                                                        #
# USAGE:                                                                 #
# ./kubectl-halloween get <resource_type>                                #
##########################################################################

#echo "Vous avez passé $# paramètres"

# Select emoji randomly
EMOJIS=(🎃 👻 🧟 🧛 🕷️ 🧙)
SELECTED_EMOJI=${EMOJIS[$RANDOM % ${#EMOJIS[@]}]};

# Usage
if [[ "$1" == "" || "$1" == "-h" || "$1" == "--help" ]]
then
    n=$'\n'
    usage="Display Halloween emoji randomly just before resources name.${n}${n}Usage:${n}   kubectl halloween get <resource_type>"

    echo "$usage" 
    exit 1
fi

# Main
if [[ "$1" == "get" ]]
then
    # kubectl $* | sed -e "1 ! s/^/${SELECTED_EMOJI} /"
    # except blank line
    # kubectl $* | sed -e "/^$/! s/^/${SELECTED_EMOJI} /"
    # except line starting with NAME
    kubectl $* | sed -e "/^NAME/ ! s/^/${SELECTED_EMOJI} /"
else
    kubectl $*
fi

#TODO: 
# afficher des emojis differents selon le type de ressource en random
# pour ne pas ajouter l'emoji pour les blank line et les lignes avec "NAME.."